### ISSUE TITLE
misdirected link on yaq.fyi  to this issues page

### ISSUE THREAD

**Issue by nfortune** [yaq-project/yaq-fyi#73]
Hello - thank you for your work developing yaq.  I'm writing to call to your attention several broken/misdirected/outdated links I've encountered on the yaq.fyi web site (as I seek to learn if  yaq would be a manageable way of direct hardware communication for my project). 

Here is the first of the links needing correction: the contact page https://yaq.fyi/contact/  directs me to the discontinued GitLab issues page instead of this one on GitHub. 

_We would love to hear from you! It's typically best to start by opening an issue on [yaq-fyi](https://gitlab.com/yaq/yaq-fyi/-/issues). We treat this issue tracker as a general forum, so please do not hesitate to open an issue for any reason! We will redirect you if necessary._

**Comment by untzag** [comment]
thanks so much @nfortune
