### ISSUE TITLE
misdirected link on yaq.fyi blog post re yaqc

### ISSUE THREAD

**Issue by nfortune** [yaq-project/yaq-fyi#74]
https://yaq.fyi/blog/yaqc-cmds/ directs viewers to the YouTube Video illustrating how to create a yaq daemon to communicate with the New-Era_NE1000 pump at https://www.youtube.com/watch?v=3G7bgBKsteI&t=1s 

instead of to the video illustrating the use of yaqc-cmds  at 

https://www.youtube.com/watch?v=ZXUBd_LM5k8

**Comment by untzag** [comment]
thanks again @nfortune :smile:
